# Example of using the distribution containers


site1dbvol:
  image: busybox
#  volumes:
#   - volumes/mysql:/var/lib/mysql

site1databasedump:
  image: ezpublishdocker_databasedump

site1vardir:
  image: ezpublishdocker_vardir

site1ezpublishvol:
  image: ezpublishdocker_distribution
  volumes_from:
   - site1vardir

site1db1:
  image: mariadb:latest
  volumes_from:
   - site1dbvol
  environment:
   - MYSQL_ROOT_PASSWORD=mysecretrootpassword
   - MYSQL_USER=ezp
   - MYSQL_PASSWORD
   - MYSQL_DATABASE=ezp
  restart: always

site1phpfpm1:
  # docker compose does not allow to specify container name, this is what it generates, might be fixed in 1.3
  image: ezsystems/ezphp
  links:
   - site1db1:db
  volumes_from:
   - site1ezpublishvol
  environment:
   - EZ_KICKSTART
   - EZ_KICKSTART_FROM_TEMPLATE
   - EZ_MAILER_TRANSPORT
   - EZ_MAILER_HOST
   - EZ_MAILER_USER
   - EZ_MAILER_PASSWORD
   - SYMFONY_ENV
   - MYSQL_PASSWORD
  restart: always

site1web1:
  image: nginx
  links:
   - site1phpfpm1:php_fpm
  volumes_from:
   - site1ezpublishvol
  volumes:
   - ./volumes/ezpublish/doc/nginx/ez-host.template:/etc/nginx/conf.d/ez-host.template
   - ./volumes/ezpublish/doc/nginx/ez_params.d:/etc/nginx/ez_params.d
  ports:
   - "8081:80"
  environment:
   - WEB_HOST=foobar.com
   - WEB_HOST_ALIAS=www.foobar.com
   - WEB_PORT=80
   - WEB_BASEDIR=/var/www
   - NGINX_CLIENT_MAX_BODY_SIZE=20m
   - NGINX_FASTCGI_PASS=php_fpm:9000
   - NGINX_FASTCGI_READ_TIMEOUT=190s
   - NGINX_EZ_PROD_REWRITE_PARAMS=include ez_params.d/ez_prod_rewrite_params;
   - SYMFONY_ENV
   - SYMFONY_DEBUG=0
   - SYMFONY_HTTP_CACHE=1
   - SYMFONY_TRUSTED_PROXIES=
   - DOCKER0NET
  command: /bin/bash -c "apt-get update && apt-get install -y gettext-base && envsubst < /etc/nginx/conf.d/ez-host.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  restart: always

site1initialize:
  image: ezsystems/ezphp
  links:
   - site1db1:db
  volumes_from:
   - site1ezpublishvol
   - site1databasedump
  environment:
   - EZ_KICKSTART
   - EZ_KICKSTART_FROM_TEMPLATE
   - SYMFONY_ENV
   - MYSQL_USER=ezp
   - MYSQL_PASSWORD
   - MYSQL_DATABASE=ezp
  command: /prepare_distribution_volume.sh

