# Default container setup
# Simple single server setup
# Uses Debian Jessie and official images when possible


dbvol:
  image: debian:jessie
  volumes:
   - ./volumes/mysql:/var/lib/mysql

ezpublishvol:
  image: debian:jessie
  volumes:
   - ./volumes/ezpublish:/var/www

db1:
  image: mariadb:latest
  volumes_from:
   - dbvol
  volumes:
   - ./resources/database_character_set.sh:/docker-entrypoint-initdb.d/database_character_set.sh
  environment:
   - MYSQL_ROOT_PASSWORD=mysecretrootpassword
   - MYSQL_USER=ezp
   - MYSQL_PASSWORD
   - MYSQL_DATABASE=ezp
   - TERM=dumb

phpfpm1:
  # docker compose does not allow to specify container name, this is what it generates, might be fixed in 1.3
  image: ezsystems/ezphp
  links:
   - db1:db
#   - solr1:solr
  volumes_from:
   - ezpublishvol
  environment:
   - EZ_KICKSTART
   - EZ_KICKSTART_FROM_TEMPLATE
   - EZ_MAILER_TRANSPORT
   - EZ_MAILER_HOST
   - EZ_MAILER_USER
   - EZ_MAILER_PASSWORD
   - SYMFONY_ENV
   - MYSQL_PASSWORD

web1:
  image: nginx
  links:
   - phpfpm1:php_fpm
  volumes_from:
   - ezpublishvol
  volumes:
   - ./volumes/ezpublish/doc/nginx/ez-host.template:/etc/nginx/conf.d/ez-host.template
   - ./volumes/ezpublish/doc/nginx/ez_params.d:/etc/nginx/ez_params.d
  ports:
   - "8080:80"
  environment:
   - WEB_HOST=foobar.com
   - WEB_HOST_ALIAS=www.foobar.com
   - WEB_PORT=80
   - WEB_BASEDIR=/var/www
   - NGINX_CLIENT_MAX_BODY_SIZE=20m
   - NGINX_FASTCGI_PASS=php_fpm:9000
   - NGINX_FASTCGI_READ_TIMEOUT=190s
   - NGINX_EZ_PROD_REWRITE_PARAMS=include ez_params.d/ez_prod_rewrite_params;
   - SYMFONY_ENV
   - SYMFONY_DEBUG=0
   - SYMFONY_HTTP_CACHE=1
   - SYMFONY_TRUSTED_PROXIES=
   - VARNISH_ENABLED
   - DOCKER0NET
  command: /bin/bash -c "apt-get update && apt-get install -y gettext-base && envsubst < /etc/nginx/conf.d/ez-host.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

#
#varnish:
#  build: dockerfiles/internal/varnish
#  links:
#   - phpfpm:php_fpm
#   - nginx:nginx
#  volumes_from:
#   - ezpublishvol
#  ports:
#   - "8081:80"
#  environment:
#   - VARNISH_ENABLED
